FROM {{ image }}

RUN OS_RELEASE=$(cat /etc/os-release); if echo "$OS_RELEASE" | grep -q "alpine"; then apk --update add --no-cache python-dev build-base; fi;

{% set project_name = project_dir.split('/')[-2] %}

RUN mkdir -p /devwork/
RUN chown :4000 /devwork
RUN chmod 775 /devwork

RUN printf {{ pypi_packs }} > /devwork/test-requirements.txt
RUN python -m pip install -r /devwork/test-requirements.txt

COPY / /devwork/{{ project_name }}

WORKDIR /devwork/{{ project_name }}

ENTRYPOINT ["/bin/sh", "-c"]
